// src/constants/permissions.js
export const PERMISSIONS = {
    TASK_CREATE: "TASK_CREATE",
    TASK_ASSIGN: "TASK_ASSIGN",
    TASK_VIEW_ALL: "TASK_VIEW_ALL",
    TASK_UPDATE_STATUS: "TASK_UPDATE_STATUS",
    USER_MANAGE: "USER_MANAGE",
    TASK_SET_DUEDATE: "TASK_SET_DUEDATE",

    ROLE_MANAGE: "ROLE_MANAGE",
    SYSTEM_CONFIG: "SYSTEM_CONFIG",
    REPORT_VIEW: "REPORT_VIEW",

    TASK_VIEW_DEPARTMENT: "TASK_VIEW_DEPARTMENT",
    TASK_APPROVE: "TASK_APPROVE",
    TASK_REVIEW_STATUS: "TASK_REVIEW_STATUS",

    TASK_VIEW_ASSIGNED: "TASK_VIEW_ASSIGNED",
    TASK_COMMENT: "TASK_COMMENT"
};
